exp_name: default
output_dir:
  type: add
  a: "/workspace/results/"
  b: "@/exp_name"
seed: 100

# data config
num_nodes: 15
dim_node: 2
num_samples: 1000

# generator
generator:
  type: Generator
  num_nodes: "@/num_nodes"
  dim_node: "@/dim_node"

# policies
policies:
  - type: RandomPolicy
  - type: GreedyPolicy
  - "@/pointernetpolicy"

# Annealing
annealing:
  timelimit: 1
  start_tmp: 0.05
  end_tmp: 0.001
  two_opt:
    type: TwoOptPolicy
    start_tmp: "@/annealing/start_tmp"
    end_tmp: "@/annealing/end_tmp"
    timelimit: "@/annealing/timelimit"
  three_opt:
    type: ThreeOptPolicy
    start_tmp: "@/annealing/start_tmp"
    end_tmp: "@/annealing/end_tmp"
    timelimit: "@/annealing/timelimit"

# PointerNetPolicy
pointernetpolicy:
  type: PointerNetPolicy
  model:
    type: PointerNet
    input_size: "@/dim_node"
    hidden_size: 128
    num_layers: 2
    search_method: "probabilistic"
  ckpt_path: "/workspace/results/pointernet/exp001/last.ckpt"
  device: cuda:0

