version: '3.5'

services:
  gpu:
    runtime: nvidia
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./:/workspaces
      - /dev/shm:/dev/shm
    working_dir: /workspaces
    ports:
      - "8888:8888"
    tty: true
  cpu:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/workspaces
      - /dev/shm:/dev/shm
    working_dir: /workspaces
    ports:
      - "9999:9999"
    tty: true
